# This file was generated by GoReleaser. DO NOT EDIT.
cask "sshto" do
  name "sshto"
  desc "Fast SSH connection manager with interactive TUI"
  homepage "https://github.com/codoworks/sshto"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sshto"

  on_macos do
    on_intel do
      url "https://github.com/codoworks/sshto/releases/download/v#{version}/sshto_#{version}_darwin_amd64.tar.gz"
      sha256 "a09a1beec4e7df7fcc3486c3df80a7e6a67d69ee0ac0c8f446546444f15357fd"
    end
    on_arm do
      url "https://github.com/codoworks/sshto/releases/download/v#{version}/sshto_#{version}_darwin_arm64.tar.gz"
      sha256 "6da00fe5c181bc411b95996507ab6581a9b2291b5f3c24376368a956c9d19c3b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/codoworks/sshto/releases/download/v#{version}/sshto_#{version}_linux_amd64.tar.gz"
      sha256 "cf58be9c7f4cd4d6240d5d6982a09bae71612261d18d38dcaa492ed142041c8d"
    end
    on_arm do
      url "https://github.com/codoworks/sshto/releases/download/v#{version}/sshto_#{version}_linux_arm64.tar.gz"
      sha256 "3f52a0a8fce061500ea7a2fda7ce38d7faf2cf79c4a5cab2c0b2705ccdfcd9fb"
    end
  end

  # No zap stanza required
end
