# This file was generated by GoReleaser. DO NOT EDIT.
cask "sshto" do
  name "sshto"
  desc "Fast SSH connection manager with interactive TUI"
  homepage "https://github.com/codoworks/sshto"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sshto"

  on_macos do
    on_intel do
      url "https://github.com/codoworks/sshto/releases/download/v#{version}/sshto_#{version}_darwin_amd64.tar.gz"
      sha256 "ecbccabcc7b84c47d2260878f5d56bff90c3b6a43d932a1d27175329fbe5274a"
    end
    on_arm do
      url "https://github.com/codoworks/sshto/releases/download/v#{version}/sshto_#{version}_darwin_arm64.tar.gz"
      sha256 "b121e0e44377875dee02c1795ac0cf0f3d80d33bb9527fc56c73f4792017e03d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/codoworks/sshto/releases/download/v#{version}/sshto_#{version}_linux_amd64.tar.gz"
      sha256 "d8e9958f2618c2f757586c75d887b7d5e6192b165b9ad33e10c3e8569c6be297"
    end
    on_arm do
      url "https://github.com/codoworks/sshto/releases/download/v#{version}/sshto_#{version}_linux_arm64.tar.gz"
      sha256 "0bb44977c5830aba0e03c9d27cae62cb1a6509c6359d72c0ec0ee6c543c0e7a4"
    end
  end

  caveats do
    "To get started, run:"
    "  sshto --help"
  end

  # No zap stanza required
end
