# This file was generated by GoReleaser. DO NOT EDIT.
cask "sshto" do
  name "sshto"
  desc "Fast SSH connection manager with interactive TUI"
  homepage "https://github.com/codoworks/sshto"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sshto"

  on_macos do
    on_intel do
      url "https://github.com/codoworks/sshto/releases/download/v#{version}/sshto_#{version}_darwin_amd64.tar.gz"
      sha256 "5e03ba5db8a48458e229438ce949789c0028973dedfc07a2420326e143658999"
    end
    on_arm do
      url "https://github.com/codoworks/sshto/releases/download/v#{version}/sshto_#{version}_darwin_arm64.tar.gz"
      sha256 "a702b85cd878b0ebd200dcee2ceaad6edd3fca274de7fd32993a7ebb4d68378a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/codoworks/sshto/releases/download/v#{version}/sshto_#{version}_linux_amd64.tar.gz"
      sha256 "61e95c724ff32c3d01fffea6a96a5e9a8faf8cd043f38adc7dfa5e779f32b6f1"
    end
    on_arm do
      url "https://github.com/codoworks/sshto/releases/download/v#{version}/sshto_#{version}_linux_arm64.tar.gz"
      sha256 "76e50db5ba2539c76360e5483c7d7b97dd4cd7da69e04464af84fc2725506cd9"
    end
  end

  # No zap stanza required
end
